# Generated by Django 3.0.2 on 2020-03-05 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasticApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_month_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_note',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='entry',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='transaction date'),
        ),
    ]
