# Generated by Django 3.0.2 on 2020-03-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasticApp', '0002_auto_20200304_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='overallTotals',
        ),
        migrations.AddField(
            model_name='category',
            name='overall_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='overall',
            name='owningUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fantasticApp.User'),
        ),
    ]
