# Generated by Django 3.0.2 on 2020-05-03 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fantasticApp', '0003_auto_20200316_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='transaction date'),
        ),
    ]
